name: Test and Approve

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run Jest tests
      id: run-tests
      run: |
        npm test -- --json --outputFile=test-results.json || true

    - name: Count passing tests
      id: count-tests
      run: |
        passed=$(jq '.numPassedTests' test-results.json)
        echo "passed=$passed" >> $GITHUB_OUTPUT

    - name: Notify student
      run: |
        echo "Student ${{ steps.evaluate.outputs.approval }}"
